const cities = [
  {
    name: "New York",
    timezone: "America/New_York",
    flag: "🇺🇸",
    fact: "Known as 'The Big Apple', it's home to Times Square and Wall Street.",
  },
  {
    name: "London",
    timezone: "Europe/London",
    flag: "🇬🇧",
    fact: "Big Ben is actually the nickname for the Great Bell, not the clock.",
  },
  {
    name: "Tokyo",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
    fact: "Tokyo is the most populous metropolitan area in the world.",
  },
  {
    name: "Cape Town",
    timezone: "Africa/Johannesburg",
    flag: "🇿🇦",
    fact: "Table Mountain is one of the oldest mountains on Earth.",
  },
  {
    name: "Sydney",
    timezone: "Australia/Sydney",
    flag: "🇦🇺",
    fact: "Sydney Opera House is made up of over 1 million roof tiles.",
  },
  {
    name: "Los Angeles",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
    fact: "Known for Hollywood, LA is the entertainment capital of the world.",
  },
  {
    name: "Paris",
    timezone: "Europe/Paris",
    flag: "🇫🇷",
    fact: "The Eiffel Tower was originally meant to be dismantled after 20 years.",
  },
  {
    name: "Berlin",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
    fact: "Berlin has more bridges than Venice — over 1,700 of them.",
  },
  {
    name: "Moscow",
    timezone: "Europe/Moscow",
    flag: "🇷🇺",
    fact: "Moscow's metro stations are known as 'underground palaces'.",
  },
  {
    name: "Dubai",
    timezone: "Asia/Dubai",
    flag: "🇦🇪",
    fact: "Home to Burj Khalifa — the tallest building in the world.",
  },
  {
    name: "Mumbai",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
    fact: "Mumbai is the financial capital of India and home to Bollywood.",
  },
  {
    name: "Beijing",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
    fact: "Beijing is home to the Forbidden City and Tiananmen Square.",
  },
  {
    name: "São Paulo",
    timezone: "America/Sao_Paulo",
    flag: "🇧🇷",
    fact: "São Paulo is the largest city in the Southern Hemisphere.",
  },
  {
    name: "Mexico City",
    timezone: "America/Mexico_City",
    flag: "🇲🇽",
    fact: "Built over a lake, Mexico City is slowly sinking each year.",
  },
  {
    name: "Buenos Aires",
    timezone: "America/Argentina/Buenos_Aires",
    flag: "🇦🇷",
    fact: "Known for tango dancing and colorful La Boca district.",
  },
  {
    name: "Cairo",
    timezone: "Africa/Cairo",
    flag: "🇪🇬",
    fact: "Cairo is the gateway to the ancient Pyramids of Giza.",
  },
  {
    name: "Nairobi",
    timezone: "Africa/Nairobi",
    flag: "🇰🇪",
    fact: "Nairobi has a national park with lions and giraffes inside the city limits.",
  },
  {
    name: "Honolulu",
    timezone: "Pacific/Honolulu",
    flag: "🇺🇸",
    fact: "Located on Oahu, it's the only US state capital located in the tropics.",
  },
  {
    name: "Singapore",
    timezone: "Asia/Singapore",
    flag: "🇸🇬",
    fact: "Singapore is one of the world’s greenest cities despite its skyscrapers.",
  },
  {
    name: "Seoul",
    timezone: "Asia/Seoul",
    flag: "🇰🇷",
    fact: "Seoul is home to the world’s fastest internet speeds.",
  },
  {
    name: "Istanbul",
    timezone: "Europe/Istanbul",
    flag: "🇹🇷",
    fact: "The only city in the world that spans two continents — Europe and Asia.",
  },
  {
    name: "Jakarta",
    timezone: "Asia/Jakarta",
    flag: "🇮🇩",
    fact: "Jakarta is built on a swamp and is sinking rapidly each year.",
  },
  {
    name: "Bangkok",
    timezone: "Asia/Bangkok",
    flag: "🇹🇭",
    fact: "Bangkok has the world’s longest city name in Thai language.",
  },
  {
    name: "Lagos",
    timezone: "Africa/Lagos",
    flag: "🇳🇬",
    fact: "Lagos is Africa’s most populous city and a major tech hub.",
  },
  {
    name: "Toronto",
    timezone: "America/Toronto",
    flag: "🇨🇦",
    fact: "Toronto is home to the CN Tower, once the world’s tallest freestanding structure.",
  },
];

export default cities;
